:important-caption: ⚠️

= Prerequisites

The setup is currently based on a single AWS account. All environments are deployed into that account. The deployment is done via GitHub Actions by pushing to the respective Git branch. Terraform is used to deploy the application. The Terraform state of these environments is separated by splitting them into different files (S3 keys).

== Switch to Region
Unless otherwise specified, all resources must be created in `eu-central-1`  (Frankfurt).

== Create OIDC Provider in AWS
[source]
----
IAM → Identity providers → Add provider
Provider-Type: OpenID Connect
Provider URL: https://token.actions.githubusercontent.com
Audience: sts.amazonaws.com
----

== Create Role for CI Pipeline
[source]
----
IAM → Roles → Create Role
Trusted entity type: Web identity
Identity provider: token.actions.githubusercontent.com
Audience: sts.amazonaws.com
GitHub organization: Planning-Poker-Teams
Add AdministratorAccess Policy (TODO: be more restrictive?)
Name: github-oidc-role
----

== Create S3 Bucket for Terraform
[source]
----
S3 → Buckets → Create bucket
Bucket Name: estim8-deploy-state
Bucket Versioning: Enable
----

== Create Dynamo Table for Terraform
[source]
----
DynamoDB → Tables → Create table
Table name: estim8-deploy-state-locks
Partition key: LockID
----

== Domain & DNS
[source]
----
Route 53 -> Registered domains -> Register Domain
----

== TLS Certificate

[IMPORTANT]
The certificate must be created twice in different regions. This is because Cloudfront requires its certificates in `us-east-1`, while the API Gateway V2 expects a "local" certificate in `eu-central-1`.

=== Request Certificate in `us-east-1`
[source]
----
Switch region to `us-east-1`
Certificate Manager -> Request certificate
Certificate type: Request a public certificate
Fully qualified domain names:
    *.estim8.cards
    estim8.cards
Validation method: DNS validation
----

=== Validate Certificate in `us-east-1`
[source]
----
Certificate Manager -> List certificates -> *.estim8.cards -> Create records in Route 53
----

=== Request Certificate in `eu-central-1`
[source]
----
Switch back to region `eu-central-1`
Certificate Manager -> Request certificate
Certificate type: Request a public certificate
Fully qualified domain names:
    *.estim8.cards
    estim8.cards
Validation method: DNS validation
----

=== Validate Certificate in `eu-central-1`
[source]
----
Additional configuration in Route 53/DNS is not needed
----

=== Wait for validation
Wait for the Domain registration and the validation of both certificates.
