name: Build & Deploy

on:
  push:
    branches:
      - production
      - develop
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        if: github.event.action != closed
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Yarn Install
        if: github.event.action != closed
        run: yarn install --immutable

      - name: Yarn Lint
        if: github.event.action != closed
        run: |
          yarn workspace backend lint
          yarn workspace frontend lint

      - name: Yarn Build
        if: github.event.action != closed
        run: |
          yarn workspace backend build
          yarn workspace frontend build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::054552196453:role/github-oidc-role
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: 'infrastructure'
        run: |
          terraform init \
            -backend-config="region=eu-central-1" \
            -backend-config="bucket=planning-poker-terraform-state" \
            -backend-config="dynamodb_table=planning-poker-terraform-state-locks" \
            -backend-config="key=${GITHUB_REF##*/}.tfstate"

      - name: Terraform Lint
        if: github.event.action != closed
        working-directory: 'infrastructure'
        run: |
          terraform fmt -check

      - name: Terraform Plan
        if: github.event.action != closed
        working-directory: 'infrastructure'
        run: |
          terraform plan \
            -var environment="${GITHUB_REF##*/}" \
            -out=plan.tfout

      - name: Terraform Apply
        if: github.event.action != closed
        working-directory: 'infrastructure'
        run: |
          terraform apply \
            -auto-approve \
            plan.tfout

      - name: Print debug
        working-directory: 'infrastructure'
        env:
          DEBUG_GITHUB_JSON: ${{ toJson(github) }}
        run: |
          echo "DEBUG_GITHUB_JSON"

      - name: Terraform Destroy
        if: github.event.action == closed
        working-directory: 'infrastructure'
        run: |
          terraform destroy \
            -var environment="${GITHUB_REF##*/}" \
            -auto-approve \
